// CMS-1500 claim form generation (HTML version for printing/submission)

export type Cms1500Data = {
  claimNumber: string
  providerName: string
  providerAddress: string
  providerPhone: string
  providerNpi: string
  payerName: string
  payerAddress: string
  patientName: string
  patientDob: string
  patientGender: string
  patientAddress: string
  patientPhone: string
  patientMedicaidId: string
  insuredName: string
  insuredMedicaidId: string
  serviceDate: string
  cptCode: string
  modifier: string
  diagnosisCode: string
  charges: string
  providerSignature: string
}

export function generateCms1500Html(data: Cms1500Data): string {
  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>CMS-1500 - ${data.claimNumber}</title>
<style>
  @page { size: letter; margin: 0.5in; }
  body { font-family: 'Courier New', monospace; font-size: 10px; color: #000; margin: 0; padding: 20px; }
  h1 { text-align: center; font-size: 14px; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 8px; }
  td, th { border: 1px solid #000; padding: 4px 6px; vertical-align: top; font-size: 9px; }
  .label { font-weight: bold; background: #f5f5f5; width: 30%; }
  .value { width: 70%; }
  .section-title { background: #e0e0e0; font-weight: bold; text-align: center; padding: 3px; font-size: 9px; }
  .claim-num { text-align: right; font-size: 9px; color: #555; margin-bottom: 4px; }
  .footer { text-align: center; font-size: 8px; color: #888; margin-top: 20px; border-top: 1px solid #ccc; padding-top: 8px; }
</style>
</head>
<body>
<div class="claim-num">Claim: ${data.claimNumber}</div>
<h1>CMS-1500 HEALTH INSURANCE CLAIM FORM</h1>

<table><tr><td colspan="2" class="section-title">1. PROVIDER INFORMATION</td></tr>
<tr><td class="label">Name</td><td class="value">${data.providerName}</td></tr>
<tr><td class="label">Address</td><td class="value">${data.providerAddress}</td></tr>
<tr><td class="label">Phone</td><td class="value">${data.providerPhone}</td></tr>
<tr><td class="label">NPI</td><td class="value">${data.providerNpi}</td></tr></table>

<table><tr><td colspan="2" class="section-title">2. PAYER INFORMATION</td></tr>
<tr><td class="label">Name</td><td class="value">${data.payerName}</td></tr>
<tr><td class="label">Address</td><td class="value">${data.payerAddress}</td></tr></table>

<table><tr><td colspan="2" class="section-title">3. PATIENT INFORMATION</td></tr>
<tr><td class="label">Name</td><td class="value">${data.patientName}</td></tr>
<tr><td class="label">DOB</td><td class="value">${data.patientDob}</td></tr>
<tr><td class="label">Gender</td><td class="value">${data.patientGender}</td></tr>
<tr><td class="label">Address</td><td class="value">${data.patientAddress}</td></tr>
<tr><td class="label">Phone</td><td class="value">${data.patientPhone}</td></tr>
<tr><td class="label">Medicaid ID</td><td class="value">${data.patientMedicaidId}</td></tr></table>

<table><tr><td colspan="2" class="section-title">4. INSURED INFORMATION</td></tr>
<tr><td class="label">Name</td><td class="value">${data.insuredName}</td></tr>
<tr><td class="label">Medicaid ID</td><td class="value">${data.insuredMedicaidId}</td></tr></table>

<table><tr><td colspan="4" class="section-title">5. SERVICES</td></tr>
<tr><th style="width:25%">Service Date</th><th style="width:35%">CPT/HCPCS</th><th style="width:10%">Mod</th><th style="width:30%">Charges</th></tr>
<tr><td>${data.serviceDate}</td><td>${data.cptCode}</td><td>${data.modifier}</td><td>$${data.charges}</td></tr></table>

<table><tr><td colspan="2" class="section-title">6. DIAGNOSIS</td></tr>
<tr><td class="label">Primary Diagnosis</td><td class="value">${data.diagnosisCode}</td></tr></table>

<table><tr><td colspan="2" class="section-title">7. SIGNATURE</td></tr>
<tr><td class="label">Provider Signature</td><td class="value">${data.providerSignature}</td></tr></table>

<div class="footer">Generated by CareIntake 245D Suite · This is a computer-generated claim form.</div>
</body></html>`
}
